# Generated by Django 4.2.2 on 2023-07-03 16:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_berita_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='foto_profil_url',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='is_adminsi',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='is_koperasi',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='is_umkm',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='details',
            name='foto_profil_url',
        ),
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='akun',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
